### ISSUE TITLE
Encountered issues in merging multiple estimated trajectories and in merging ground truth trajectories，both in covins and covin_g

### ISSUE THREAD

**Issue by NatureLan-sudo** [manthan99/covins_g#2]
I merge multiple trajectory information obtained from the system output using the "cat" command and visualize them using "evo". I am facing an issue where the endpoint of the first trajectory is connected to the starting point of the second trajectory, resulting in a line. How can I solve this problem? This is crucial for trajectory evaluation. Will the manual merging mentioned in the readme resolve this issue? Could you please advise me on what to do? I apologize for the disturbance and hope your help.
@manthan99 
![](https://secure2.wostatic.cn/static/fdzEH8xXpcg3JdVseZPAxK/image.png?auth_key=1683966475-4M2PQm5uC7CHnG58eFpfMg-0-0ccb47067d857e5a7b32e53099359983)

**Comment by manthan99** [comment]
Hi

As far as I know, this is just a visualization issue and the error wouldn't reflect in the quantitative results since the error is computed between the estimated and GT poses and ideally there isn't any estimated KF in that connecting line.

I hope this helps.

Best
Manthan
